repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: flake8
        name: flake8
        entry: flake8 .
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: pyupgrade
        name: Pyupgrade
        entry: pyupgrade --py310-plus
        types: [ python ]
        language: system
        exclude: ^(docs/|semente_cli/)
        fail_fast: true

      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true