repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true